CREATE TABLE DM_PROCESSED.EMPLOYEE
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
  ,ADDRESS VARCHAR
  ,PHONENUMBER VARCHAR
  ,PINCODE INTEGER
);

alter table DM_PROCESSED.HELLO_WORLD add column DESCRIPTION VARCHAR;